//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JibresBooster1.translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JibresBooster1.translation.fa", typeof(fa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خداحافظ.
        /// </summary>
        internal static string Bye {
            get {
                return ResourceManager.GetString("Bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارمایل.
        /// </summary>
        internal static string Ermile {
            get {
                return ResourceManager.GetString("Ermile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در راه‌اندازی.
        /// </summary>
        internal static string ErrorInit {
            get {
                return ResourceManager.GetString("ErrorInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سلام.
        /// </summary>
        internal static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جیبرس.
        /// </summary>
        internal static string Jibres {
            get {
                return ResourceManager.GetString("Jibres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جیبرس بوستر.
        /// </summary>
        internal static string JibresBooster {
            get {
                return ResourceManager.GetString("JibresBooster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جیبرس بوستر۱.
        /// </summary>
        internal static string JibresBooster1 {
            get {
                return ResourceManager.GetString("JibresBooster1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در اجرای جیبرس بوستر.
        /// </summary>
        internal static string MsgAppError {
            get {
                return ResourceManager.GetString("MsgAppError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان راه‌اندازی سرور داخلی وجود ندارد.
        /// </summary>
        internal static string MsgAppErrorServer {
            get {
                return ResourceManager.GetString("MsgAppErrorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جیبرس بوستر بسته شد.
        /// </summary>
        internal static string MsgAppExit {
            get {
                return ResourceManager.GetString("MsgAppExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جیبرس بوستر آماده به‌کار است.
        /// </summary>
        internal static string MsgAppStart {
            get {
                return ResourceManager.GetString("MsgAppStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باز کردن برنامه.
        /// </summary>
        internal static string OpenWindow {
            get {
                return ResourceManager.GetString("OpenWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست.
        /// </summary>
        internal static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توجه.
        /// </summary>
        internal static string Warn {
            get {
                return ResourceManager.GetString("Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وب‌سایت.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
